//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneAPI_bt01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int PID { get; set; }
        public string PName { get; set; }
        public Nullable<long> PPrice { get; set; }
        public string Status { get; set; }
    }
}
